# Generated by Django 6.0.2 on 2026-02-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_reservations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='show_id',
            new_name='show',
        ),
    ]
