# Generated by Django 6.0.2 on 2026-02-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_rename_show_id_reservations_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='show',
            new_name='show_id',
        ),
    ]
