# Generated by Django 6.0.2 on 2026-02-11 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('seats', models.IntegerField()),
                ('status', models.CharField(choices=[('Reservado', 'Reserved'), ('Confirmado', 'Comfirmed'), ('Cancelado', 'Cancelled')], default='Reservado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shows', to='shows.shows')),
            ],
        ),
    ]
